version: '3.6'

services:
  web:
    container_name: web
    build: ./
    command: npm run web-server
    working_dir: /usr/src/tic-tac-toe
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/tic-tac-toe
    links:
        - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    